src/Web/Controllers/ChatController.cs
using Microsoft.AspNetCore.Mvc;

namespace Template.Web.Controllers;

public class ChatController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

src/Web/Controllers/LocalizationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using System;
using Template.Application.Services;

namespace Template.Web.Controllers;

public class LocalizationController : Controller
{
    private readonly ILocalizationService _localizationService;

    public LocalizationController(ILocalizationService localizationService)
    {
        _localizationService = localizationService;
    }

    public IActionResult SetLanguage(string culture, string returnUrl)
    {
        Response.Cookies.Append(
            CookieRequestCultureProvider.DefaultCookieName,
            CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
            new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
        );

        return LocalRedirect(returnUrl);
    }

    [AllowAnonymous]
    public IActionResult GetLocalizedStrings()
    {
        var localizedStrings = _localizationService.GetLocalizedStrings();

        return Json(localizedStrings);
    }
}

src/Web/Controllers/ReportController.cs
using DevExpress.AspNetCore.Reporting.QueryBuilder;
using DevExpress.AspNetCore.Reporting.ReportDesigner;
using DevExpress.AspNetCore.Reporting.WebDocumentViewer;
using DevExpress.XtraReports.UI;
using DevExpress.XtraReports.Web.ReportDesigner;
using DevExpress.XtraReports.Web.WebDocumentViewer;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Template.Infrastructure.Persistence;
using Template.Infrastructure.PredefinedReports;
using Template.Web.Models;

namespace Template.Web.Controllers;

public class ReportController : Controller
{
    private readonly ReportDbContext _context;

    public ReportController(ReportDbContext context)
    {
        _context = context;
    }

    public List<ReportListViewModel> GetReportList()
    {
        List<ReportListViewModel> reportsList = new();
        List<ReportListViewModel> predefinedReports = ReportsFactory.Reports.Select(m => new ReportListViewModel { Name = m.Key, DisplayName = m.Key, IsCustomReport = false }).ToList();
        List<ReportListViewModel> savedReports = _context.Reports.Select(m => new ReportListViewModel { Name = m.Name, DisplayName = m.DisplayName, IsCustomReport = true }).ToList();

        reportsList.AddRange(predefinedReports);
        reportsList.AddRange(savedReports);

        return reportsList;
    }

    [HttpDelete]
    public async Task<IActionResult> DeleteReportAsync(string reportName, CancellationToken cancellationToken)
    {
        var toDelete = _context.Reports.FirstOrDefault(m => m.Name == reportName);
        if (toDelete is null)
            return Conflict("Report not found!");

        _context.Remove(toDelete);
        await _context.SaveChangesAsync(cancellationToken).ConfigureAwait(true);

        return Ok();
    }

    public async Task<IActionResult> Designer(
            [FromServices] IReportDesignerClientSideModelGenerator clientSideModelGenerator,
            [FromQuery] string reportName)
    {
        ReportDesignerCustomModel model = new ReportDesignerCustomModel();
        model.ReportDesignerModel = await CreateDefaultReportDesignerModel(clientSideModelGenerator, reportName, null);
        return View(model);
    }

    public static Dictionary<string, object> GetAvailableDataSources()
    {
        var dataSources = new Dictionary<string, object>();
        return dataSources;
    }

    public static async Task<ReportDesignerModel> CreateDefaultReportDesignerModel(IReportDesignerClientSideModelGenerator clientSideModelGenerator, string reportName, XtraReport report)
    {
        reportName = string.IsNullOrEmpty(reportName) ? "TestReport" : reportName;
        var dataSources = GetAvailableDataSources();
        if (report != null)
        {
            return await clientSideModelGenerator.GetModelAsync(report, dataSources, ReportDesignerController.DefaultUri, WebDocumentViewerController.DefaultUri, QueryBuilderController.DefaultUri);
        }
        return await clientSideModelGenerator.GetModelAsync(reportName, dataSources, ReportDesignerController.DefaultUri, WebDocumentViewerController.DefaultUri, QueryBuilderController.DefaultUri);
    }

    public async Task<IActionResult> Viewer(
        [FromServices] IWebDocumentViewerClientSideModelGenerator clientSideModelGenerator,
        [FromQuery] string reportName)
    {
        var reportToOpen = string.IsNullOrEmpty(reportName) ? "TestReport" : reportName;
        var model = new ViewerModel
        {
            ViewerModelToBind = await clientSideModelGenerator.GetModelAsync(reportToOpen, WebDocumentViewerController.DefaultUri)
        };
        return View(model);
    }
}

src/Web/Controllers/Setup/ModuleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Template.Application.Interfaces.Setup.ModuleRepository;
using Template.Domain.Common;
using Template.Domain.Dto.ModuleDto;
using Template.Web.Models;

namespace Template.Web.Controllers.Setup;

[Authorize]
public class ModuleController : Controller
{
    private readonly IModuleRepository _moduleRepository;
    private readonly IModuleTypeRepository _moduleTypeRepository;
    private readonly IModuleStageRepository _moduleStageRepository;
    private readonly IModuleSettingRepository _moduleSettingRepository;
    private readonly IModuleStageApproverRepository _stageApproverRepository;

    public ModuleController(
        IModuleRepository moduleRepository,
        IModuleTypeRepository moduleTypeRepository,
        IModuleStageRepository moduleStageRepository,
        IModuleSettingRepository moduleSettingRepository,
        IModuleStageApproverRepository stageApproverRepository)
    {
        _moduleRepository = moduleRepository;
        _moduleTypeRepository = moduleTypeRepository;
        _moduleStageRepository = moduleStageRepository;
        _moduleSettingRepository = moduleSettingRepository;
        _stageApproverRepository = stageApproverRepository;
    }

    public async Task<IActionResult> Index()
    {
        try
        {
            var moduleTypes = await _moduleTypeRepository.GetAllAsync();
            var approvalRouteTypes = new List<DropDownModel>()
                {
                    new DropDownModel { Id = 1, Description = "Straight" },
                    new DropDownModel { Id = 2, Description = "Total Count" }
                };

            var module = new ModuleModel
            {
                ApprovalRouteTypes = approvalRouteTypes.ToList()
            };

            var moduleStages = new List<ModuleStageModel> {
                    new ModuleStageModel { Name = "Review" },
                    new ModuleStageModel { Name = "Approve" }
                };

            var viewModel = new ModuleViewModel
            {
                Module = module,
                ModuleStages = moduleStages
            };

            return View(viewModel);
        }
        catch (Exception ex) { return View("error", new ErrorViewModel { Message = ex.Message, Exception = ex }); }
    }

    public async Task<IActionResult> ModuleSettings()
    {
        try
        {
            var data = await _moduleSettingRepository.GetAllAsync();
            return View(data);
        }
        catch (Exception ex) { return View("Error", new ErrorViewModel { Message = ex.Message, Exception = ex }); }
    }

    #region Modules API

    public async Task<IActionResult> GetModules() =>
        Ok(await _moduleRepository.GetAllAsync());

    public async Task<IActionResult> GetParentModules(int moduleTypeId)
    {
        try
        {
            var modules = await _moduleRepository.GetAllAsync();
            var parentModulesDropDown = modules.Where(m => m.ModuleTypeId == moduleTypeId && (m.ParentModuleId == 0 || m.ParentModuleId == null)).Select(m => new DropDownModel { Id = m.Id, Description = m.Description }).ToList();
            return Ok(parentModulesDropDown);
        }
        catch (Exception ex) { return BadRequest(ex.Message); }
    }

    public async Task<IActionResult> GetModule(int id) =>
        Ok(await _moduleRepository.GetByIdAsync(id));

    //public async Task<IActionResult> GetModuleStages(int id) =>
    //    Ok(await _moduleStageRepository.(id));

    public async Task<IActionResult> GetModuleTypes() =>
        Ok(await _moduleTypeRepository.GetAllAsync());

    public async Task<IActionResult> GetModuleType(int id) =>
        Ok(await _moduleTypeRepository.GetByIdAsync(id));

    public async Task<IActionResult> GetModuleByType(int typeId)
    {
        try
        {
            var data = await _moduleRepository.GetAllAsync();

            return Ok(data.Where(m => m.ModuleTypeId == typeId));
        }
        catch (Exception ex) { return BadRequest(ex.Message); }
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> SaveModuleType(ModuleTypeModel model)
    {
        try
        {
            if (!ModelState.IsValid)
                return Conflict(ModelState.Where(x => x.Value.Errors.Any()).Select(x => new { x.Key, x.Value.Errors }));

            int userId = int.Parse(User.Identity.Name);

            await _moduleTypeRepository.CreateAsync(model, userId);

            return Ok();
        }
        catch (Exception ex) { return BadRequest(ex.Message); }
    }

    [HttpDelete]
    [Route("Module/DeleteModuleTypes/")]
    public async Task<IActionResult> DeleteModuleTypes(string moduleTypeIds)
    {
        try
        {
            int[] Ids = Array.ConvertAll(moduleTypeIds.Split(','), int.Parse);
            await _moduleTypeRepository.BachDeleteAsync(Ids);

            return Ok();
        }
        catch (Exception ex) { return BadRequest(ex.Message); }
    }

    public async Task<IActionResult> GetStageApprovers(int id)
    {
        try
        {
            var data = await _stageApproverRepository.GetByModuleStageId(id);

            return Ok(data);
        }
        catch (Exception ex)
        {
            return BadRequest(ex.Message);
        }
    }

    public async Task<IActionResult> GetStageApprover(int id)
    {
        try
        {
            var data = await _stageApproverRepository.GetById(id);

            return Ok(data);
        }
        catch (Exception ex)
        {
            return BadRequest(ex.Message);
        }
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> SaveModule(ModuleViewModel model)
    {
        try
        {
            if (ModelState.IsValid)
            {
                var userId = int.Parse(User.Identity.Name);

                await _moduleRepository.SaveAsync(model.Module, model.ModuleStages, userId);

                return Ok();
            }
            else
            {
                var errors = ModelState.Where(x => x.Value.Errors.Any()).Select(x => new { x.Key, x.Value.Errors });
                return Conflict(errors);
            }
        }
        catch (Exception ex) { return BadRequest(ex.Message); }
    }

    [HttpDelete]
    [Route("Module/DeleteModules/")]
    public async Task<IActionResult> DeleteModules(string moduleIds)
    {
        try
        {
            int[] Ids = Array.ConvertAll(moduleIds.Split(','), int.Parse);

            if (Ids.Length > 0)
                foreach (var moduleId in Ids)
                    await _moduleRepository.DeleteAsync(moduleId);

            return Ok();
        }
        catch (Exception ex) { return BadRequest(ex.Message); }
    }

    #endregion Modules API
}

src/Web/Views/Shared/BadRequestPage.cshtml
@inject IStringLocalizer<SharedResources> localizer

@{
    Layout = null;
    var lotieLink = "https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js";
    ViewData["MainTitle"] = localizer["Robot Documentation"];
}

<html lang="en" data-bs-theme="light" data-layout-mode="fluid" data-menu-color="gradient" data-topbar-color="brand" data-layout-position="fixed" data-sidenav-size="default" data-lt-installed="true">
<head>
    <meta charset="utf-8" />
    <title>500 - Internal server error  | @ViewData["MainTitle"]</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="MNLeistung.de" name="author" />

    <!-- App favicon -->
    <link rel="shortcut icon" href="~/fac">

    <!-- Thirdparty css -->
    <link rel="stylesheet" href="~/css/thirdparty.bundle.css" id="app-style" asp-append-version="true" />
</head>

<body class="authentication-bg-img" data-sidebar-size="default" data-layout-width="fluid" data-layout-menu-position="fixed" data-sidebar-color="light" data-topbar-color="dark" style="visibility: visible; opacity: 1;">
    <div class="bg-overlay"></div>

    <div class="mt-5 mb-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <script src="@lotieLink"></script>
                    <lottie-player src="https://assets3.lottiefiles.com/packages/lf20_gs9xrxtb.json" background="transparent" speed="0.5" style="height: 75vh;" loop autoplay></lottie-player>
                    <div class="auth-logo d-none">
                        <a href="index.html" class="logo logo-dark text-center">
                            <span class="logo-lg">
                                <img src="~/CodeFox4/images/logo-dark.png" alt="" height="22">
                            </span>
                        </a>

                        <a href="index.html" class="logo logo-light text-center">
                            <span class="logo-lg">
                                <img src="~/CodeFox4/images/logo-light.png" alt="" height="22">
                            </span>
                        </a>
                    </div>

                    <div class="text-center mt-4 d-none">
                        <img src="~/CodeFox4/images/icons/globe.svg" alt="globe.svg" height="60">
                        <h1 class="display-3 fw-semibold mt-4">500</h1>
                        <p class="text-muted mt-4">Why not try refreshing your page? or you can contact <a href="#" class="text-primary">ME</a></p>

                        <a href="index.html" class="btn btn-primary waves-effect waves-light mt-3">Return Home</a>
                    </div>
                </div>
            </div> <!-- end col -->
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
    </div>
    <!-- end page -->

    <footer class="footer footer-alt">
        <script>document.write(new Date().getFullYear())</script> &copy; Robot Documentation Powered by <a href="https://mnleistung.de" class="link-dark text-decoration-underline"> MNLeistung.de</a>
    </footer>

    <!-- Thirdparty js -->
    <script src="~/js/site.thirdparty.bundle.js" asp-append-version="true"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

src/Web/Views/Shared/NotFoundPage.cshtml
@inject IStringLocalizer<SharedResources> localizer

@{
    Layout = null;
  
    ViewData["MainTitle"] = localizer["Robot Documentation"];
}

<html lang="en" data-bs-theme="light" data-layout-mode="fluid" data-menu-color="gradient" data-topbar-color="brand" data-layout-position="fixed" data-sidenav-size="default" data-lt-installed="true">
<head>
    <meta charset="utf-8" />
    <title>404 - Page not Found  | @ViewData["MainTitle"]</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="MNLeistung.de" name="author" />

    <!-- App favicon -->
    <link rel="shortcut icon" href="~/favico.png">

    <!-- Thirdparty css -->
    <link rel="stylesheet" href="~/css/thirdparty.bundle.css" id="app-style" asp-append-version="true" />
</head>

<body class="authentication-bg-img" data-sidebar-size="default" data-layout-width="fluid" data-layout-menu-position="fixed" data-sidebar-color="light" data-topbar-color="dark" style="visibility: visible; opacity: 1;">
    <div class="bg-overlay"></div>

    <div class="mt-5 mb-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="text-center">
                        <h1 class=" text-danger monospace" style="font-size: 14em;">404</h1>
                        <h2 class="text-uppercase text-primary mt-4">Page Not Found</h2>
                        <p class="text-muted mt-4 ">
                            It's looking like you may have taken a wrong turn. Don't worry... it
                            happens to the best of us. You might want to check your internet connection. Here's a
                            little tip that might help you get back on track.
                        </p>

                        <a asp-action="Index" class="btn btn-primary waves-effect waves-light mt-4"> Return Home</a>
                        <!-- <p class="">Return to <a href="index.html" class="btn btn-primary waves-effect waves-light"><b>Home</b></a></p> -->
                    </div>
                </div> <!-- end col -->
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
    </div>
    <!-- end page -->

    <footer class="footer footer-alt">
        <script>document.write(new Date().getFullYear())</script> &copy; Robot Documentation Powered by <a href="https://mnleistung.de" class="link-dark text-decoration-underline"> MNLeistung.de</a>
    </footer>

    <!-- Thirdparty js -->
    <script src="~/js/site.thirdparty.bundle.js" asp-append-version="true"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

src/Web/Views/Shared/_AuthenticationLayout.cshtml
@inject IStringLocalizer<SharedResources> localizer

@{
    Layout = null;
    ViewData["Title"] = "Log In";
    ViewData["MainTitle"] = localizer["MNL Template"];
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"] | @ViewData["MainTitle"]</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="MNLeistung.de" name="author" />

    <!-- App favicon -->
    <link rel="shortcut icon" href="~/favico.png">

    <link href="~/css/login.bundle.css" rel="stylesheet" type="text/css" id="app-style" asp-append-version="true" />
</head>

<body class="loading authentication-bg bg-light vh-100">
    <div class="account-pages vh-100">
        <div class="container authentication-container">
            <div class="card shadow-lg overflow-hidden m-0">
               @RenderBody()
            </div>
        </div>
    </div>

    <script src="~/js/login.bundle.js" asp-append-version="true"></script>
    <script src="~/js/validation.bundle.js" asp-append-version="true"></script>
    <script src="~/js/Setup/Account/LoginScript.js" asp-append-version="true"></script>
</body>
</html>

src/Web/Views/Shared/_CulturePartial.cshtml
@using Microsoft.AspNetCore.Builder;
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options
@inject IOptions<RequestLocalizationOptions> LocalizationOptions
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var currentLanguage = requestCulture?.RequestCulture.UICulture.Parent.ToString();
    var cultureItems = LocalizationOptions.Value.SupportedUICultures
        .Select(c => new { Value = c.Name, Text = c.DisplayName, c.Parent })
        .ToList();
    var returnUrl = string.IsNullOrEmpty(Context.Request.Path)
        ? "~/"
        : $"~{Context.Request.Path.Value}{Context.Request.QueryString}";
}

<li class="dropdown">
    <a class="nav-link dropdown-toggle arrow-none waves-effect waves-light" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
        <img src="~/template/CodeFox/images/flags/@(currentLanguage).jpg" alt="flag-icon" height="16">
    </a>
    <div class="dropdown-menu dropdown-menu-end dropdown-menu-animated">

        @foreach (var culture in cultureItems)
        {
            <!-- item-->
            <a asp-controller="Localization" asp-action="SetLanguage" asp-route-culture="@culture.Value" asp-route-returnUrl="@returnUrl" class="dropdown-item  @(culture.Parent.ToString() == currentLanguage ? "active" : "")">
                <img src="~/template/CodeFox/images/flags/@(culture.Parent).jpg" alt="flg-icon" class="me-1" height="12"> <span class="align-middle">@culture.Text</span>
            </a>
        }
    </div>
</li>

src/Web/Views/Shared/_Footer.cshtml
@inject IStringLocalizer<SharedResources> localizer
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                &copy; @DateTime.Now.Year - @ViewData["MainTitle"]
            </div>
            <div class="col-md-6">
                <div class="text-md-end footer-links d-none d-md-block">
                    <a href="https://mnleistung.ph/about-us">@localizer["About"]</a>
                    <a href="https://mnleistung.ph/services">@localizer["Services"]</a>
                    <a href="https://mnleistung.ph/contact-us">@localizer["Contact Us"]</a>
                </div>
            </div>
        </div>
    </div>
</footer>

src/Web/Views/Shared/_HorizontalLayout.cshtml
@inject IStringLocalizer<SharedResources> localizer

@{
    ViewData["MainTitle"] = localizer["MNL Template"];
}

<!DOCTYPE html>
<html lang="en" data-layout="topnav">

<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"] | @ViewData["MainTitle"]</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="MNLeistung.de" name="author" />

    <!-- App favicon -->
    <link rel="shortcut icon" href="~/favico.png">

    <!-- Thirdparty css -->
    @RenderSection("Links", false)

    <link rel="stylesheet" href="~/css/site.thirdparty.bundle.css" id="app-style" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>

<body>
    <input type="hidden" id="txtBaseUrl" value="@(@Url.Content("~"))/" />

    <!-- Begin page -->
    <div id="wrapper">

        <!-- ========== Topbar Start ========== -->
        <partial name="_Topbar" />
        <!-- ========== Topbar End ========== -->
        <!-- ========== Horizontal Menu Start ========== -->
        <partial name="_TopNav" />
        <!-- ========== Horizontal Menu End ========== -->
        <!-- ============================================================== -->
        <!-- Start Page Content here -->
        <!-- ============================================================== -->
        <div class="content-page">
            <div class="content">
                <!-- Start Content-->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- container -->
            </div> 
            <!-- content -->
            <!-- Footer Start -->
            <partial name="_Footer" />
            <!-- end Footer -->
        </div>
        <!-- ============================================================== -->
        <!-- End Page content -->
        <!-- ============================================================== -->
    </div>
    <!-- END wrapper -->
    <!-- Theme Settings -->
    <partial name="_ThemeSettings" />

    <!-- Thirdparty js -->
    <script src="~/js/site.thirdparty.bundle.js" asp-append-version="true"></script>
    <script src="~/lib/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/longRunningTask.js" asp-append-version="true"></script>
    <script src="~/js/sessionChecker.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @*<script src="~/js/navChangeColor.js" asp-append-version="true"></script>*@

    @RenderSection("Scripts", false)

</body>

</html>

src/Web/Views/Shared/_Layout2.cshtml
@inject IStringLocalizer<SharedResources> localizer

@{
    var lottieLink = "https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js";
    ViewData["MainTitle"] = localizer["Robot Documentation"];
}

<html lang="en" data-bs-theme="light" data-layout-mode="fluid" data-menu-color="gradient" data-topbar-color="brand" data-layout-position="fixed" data-sidenav-size="default" data-lt-installed="true">
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"] | @ViewData["MainTitle"]</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="MNLeistung.de" name="author" />

    <!-- App favicon -->
    <link rel="shortcut icon" href="~/favico.png">

    <!-- Thirdparty css -->
    <link rel="stylesheet" href="~/css/thirdparty.bundle.css" id="app-style" asp-append-version="true" />
</head>

<body class="authentication-bg-img" data-sidebar-size="default" data-layout-width="fluid" data-layout-menu-position="fixed" data-sidebar-color="light" data-topbar-color="dark" style="visibility: visible; opacity: 1;">
    <div class="bg-overlay"></div>

    <div class="mt-5 mb-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body p-3">
                            <script src="@lottieLink"></script>
                            <lottie-player src="https://assets5.lottiefiles.com/packages/lf20_inueopnr.json" background="transparent" speed="0.5" style="height: 65vh;" loop autoplay></lottie-player>
                            <div class="auth-logo">
                                <a href="index.html" class="logo logo-dark text-center">
                                    <span class="logo-lg">
                                        <img src="~/Files/logo/eiFOS.png" alt="" height="22">
                                    </span>
                                </a>

                                <a href="index.html" class="logo logo-light text-center">
                                    <span class="logo-lg">
                                        <img src="~/Files/eiFOS_Logo_2022/2_eiFOS_without border_black text.png" alt="" height="22">
                                    </span>
                                </a>
                            </div>
                            @RenderBody()
                        </div>

                    </div> <!-- end card-body -->
                    <!-- end card -->

                </div> <!-- end col -->
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
    </div>
    <!-- end page -->

    <footer class="footer footer-alt">
        <script>document.write(new Date().getFullYear())</script> &copy; Robot Documentation Powered by <a href="https://mnleistung.de" class="link-dark text-decoration-underline">MNLeistung.de</a>
    </footer>

    <!-- Thirdparty js -->
    <script src="~/js/site.thirdparty.bundle.js" asp-append-version="true"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", false)
</body>
</html>

src/Web/Views/Shared/_TopNav.cshtml
@inject IStringLocalizer<SharedResources> localizer
<div class="topnav">
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg">
            <div class="collapse navbar-collapse" id="topnav-menu-content">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index" id="topnav-dashboards" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="fe-airplay"></i>Dashboards
                        </a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-apps" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fe-grid"></i>Apps <div class="arrow-down"></div>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="topnav-apps">
                            <a asp-controller="Chat" asp-action="Index" class="dropdown-item">
                                <i class="fe-message-square me-1"></i>
                                Chat
                            </a>
                            <div class="dropdown">
                                <a class="dropdown-item dropdown-toggle arrow-none" href="#" id="topnav-crm" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fe-file me-1"></i>
                                    Report
                                    <div class="arrow-down"></div>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="topnav-crm">
                                    <a asp-controller="Report" asp-action="Viewer" class="dropdown-item">Viewer</a>
                                    <a asp-controller="Report" asp-action="Designer" class="dropdown-item">Designer</a>
                                </div>
                            </div>
                            <a asp-controller="Module" asp-action="Index" class="dropdown-item">
                                <i class="fe-file-text me-1"></i>
                                Module
                            </a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-components" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="uil-package"></i>Transaction <div class="arrow-down"></div>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="topnav-components">
                            <a asp-controller="Transaction" asp-action="Create" class="dropdown-item">
                                <i class="fe-plus-circle me-1"></i>
                                Create/Update
                            </a>
                            <a asp-controller="Transaction" asp-action="Create" class="dropdown-item">
                                <i class="fe-file-text me-1"></i>
                                Details
                            </a>
                            <a asp-controller="Transaction" asp-action="Index" class="dropdown-item">
                                <i class="fe-list me-1"></i>
                                List
                            </a>
                        </div>
                    </li>

                </ul>
            </div>
        </nav>
    </div>
</div>